# Jekyll dependencies for GitHub Pages
source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "kramdown-parser-gfm"
gem "jekyll-feed", "~> 0.12"

# GitHub Pages specific
gem "github-pages", group: :jekyll_plugins

